blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ / Documentation
    url: https://github.com/Kazu-dnssweeper/dnssweeper-cli#readme
    about: ã¾ãšã¯READMEã‚’ã”ç¢ºèªãã ã•ã„ / Please check the README first
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ / Discussions
    url: https://github.com/Kazu-dnssweeper/dnssweeper-cli/discussions
    about: ã‚¢ã‚¤ãƒ‡ã‚¢ã‚„ä¸€èˆ¬çš„ãªè³ªå•ã¯ã“ã¡ã‚‰ / For ideas and general questions